// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PeopleGen.Dal;

namespace PeopleGen.Dal.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    [Migration("20211005042236_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PeopleGen.Core.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.Property<int>("strength")
                        .HasColumnType("integer");

                    b.HasKey("PersonId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Age = 46,
                            Alignment = "Neutral Neutral",
                            Charisma = 18,
                            Constitution = 10,
                            Dexterity = 14,
                            FirstName = "Talice",
                            Gender = "Female",
                            Intelligence = 15,
                            LastName = "Nenna",
                            SpeciesId = 1,
                            Wisdom = 18,
                            strength = 10
                        },
                        new
                        {
                            PersonId = 2,
                            Age = 20,
                            Alignment = "Chaotic Neutral",
                            Charisma = 12,
                            Constitution = 116,
                            Dexterity = 13,
                            FirstName = "Narook",
                            Gender = "Male",
                            Intelligence = 11,
                            LastName = "Vunakian",
                            SpeciesId = 2,
                            Wisdom = 11,
                            strength = 20
                        },
                        new
                        {
                            PersonId = 3,
                            Age = 30,
                            Alignment = "Chaotic Neutral",
                            Charisma = 13,
                            Constitution = 19,
                            Dexterity = 19,
                            FirstName = "Denede",
                            Gender = "Male",
                            Intelligence = 18,
                            LastName = "FireStarter",
                            SpeciesId = 1,
                            Wisdom = 15,
                            strength = 10
                        });
                });

            modelBuilder.Entity("PeopleGen.Core.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            SpeciesName = "Elf"
                        },
                        new
                        {
                            SpeciesId = 2,
                            SpeciesName = "Human"
                        },
                        new
                        {
                            SpeciesId = 3,
                            SpeciesName = "Orc"
                        });
                });

            modelBuilder.Entity("PeopleGen.Core.Person", b =>
                {
                    b.HasOne("PeopleGen.Core.Species", "Species")
                        .WithMany("persons")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PeopleGen.Core.Species", b =>
                {
                    b.Navigation("persons");
                });
#pragma warning restore 612, 618
        }
    }
}
